# Generated by Django 3.2.9 on 2021-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpCheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sessionid',
            field=models.TextField(default='null'),
        ),
    ]
