# Generated by Django 3.2.9 on 2021-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpCheck', '0002_request_sessionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('session_start', models.TimeField(auto_now=True)),
            ],
        ),
    ]
