# Generated by Django 3.2.9 on 2021-11-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpCheck', '0003_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='sessionid',
            new_name='session_id',
        ),
    ]
